all: VM VMC

VM:
	g++ -Wall -fdiagnostics-color=always -g Stack.cpp VirtualMachine.cpp VMMain.cpp -o ../bin/VM

VMC:
	g++ -Wall -fdiagnostics-color=always -g Stack.cpp VirtualMachine.cpp VMC.cpp -o ../bin/VMC